import re

import pytest

from no_ai_attribution.main import find_violations, main, visible_lines

BLOCKED = [
    "Fix parser\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
    "Fix parser\n\nCo-authored-by: Claude <claude@example.com>",
    "Add hook\n\nco-authored-by: copilot-swe-agent[bot]@users.noreply.github.com",
    "Add hook\n\nAssisted-by: Codex",
    "Add hook\n\nHelped-by: AI",
    "Tidy up\n\n\N{ROBOT FACE} Generated with [Claude Code](https://claude.com/claude-code)",
    "Update docs\n\nGenerated by AI",
    "Refactor, written by ChatGPT",
    "Rework the API\n\nCreated using Gemini",
    "Ship it\n\nmade with Cursor",
    "Ship it\n\nGenerated with GPT-5",
    "Ship it \N{ROBOT FACE}",
]

ALLOWED = [
    "Fix trailing whitespace in scripts",
    "Fix bug\n\nCo-authored-by: Jane Doe <jane@example.com>",
    "Document the claude/CLAUDE.md sync script",
    "Add ai4ci cost skill",
    "Fix aircraft parser",
    "Teach the agent to read AGENTS.md",
    "Generated by the build script",
    "Co-authored-by: Aisha Khan <aisha@example.com>",
    "Bump anthropic sdk to 0.40.0",
]


@pytest.mark.parametrize("message", BLOCKED)
def test_blocked(message):
    assert find_violations(message)


@pytest.mark.parametrize("message", ALLOWED)
def test_allowed(message):
    assert find_violations(message) == []


def test_reports_the_original_line_number():
    message = "Fix parser\n\n# please enter the commit message\nCo-authored-by: Claude\n"
    assert find_violations(message) == [(4, "Co-authored-by: Claude")]


def test_ignores_comment_lines():
    assert find_violations("Fix parser\n# Co-authored-by: Claude\n") == []


def test_ignores_the_verbose_diff_below_the_scissors_line():
    message = (
        "Fix parser\n"
        "# ------------------------ >8 ------------------------\n"
        "diff --git a/x b/x\n"
        "+Co-authored-by: Claude <noreply@anthropic.com>\n"
    )
    assert find_violations(message) == []


def test_visible_lines_blanks_comments_and_stops_at_scissors():
    message = "one\n#two\n# ------------------------ >8 ------------------------\nthree\n"
    assert visible_lines(message) == ["one", ""]


def test_extra_patterns_are_honoured():
    message = "Fix parser\n\nPaired-with: RoboDev"
    assert find_violations(message) == []
    assert find_violations(message, [re.compile("robodev", re.IGNORECASE)])


def test_main_accepts_a_clean_message(tmp_path, capsys):
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text("Fix trailing whitespace\n", encoding="utf-8")
    assert main([str(path)]) == 0
    assert capsys.readouterr().out == ""


def test_main_rejects_and_reports(tmp_path, capsys):
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text("Fix x\n\nCo-authored-by: Claude\n", encoding="utf-8")
    assert main([str(path)]) == 1
    out = capsys.readouterr().out
    assert "AI attribution is not allowed" in out
    assert "line 3: Co-authored-by: Claude" in out


def test_main_takes_extra_patterns_from_the_command_line(tmp_path):
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text("Fix x\n\nPaired-with: RoboDev\n", encoding="utf-8")
    assert main([str(path)]) == 0
    assert main(["--extra-pattern", "robodev", str(path)]) == 1


def test_main_checks_every_file(tmp_path):
    clean = tmp_path / "clean"
    clean.write_text("Fix x\n", encoding="utf-8")
    dirty = tmp_path / "dirty"
    dirty.write_text("\N{ROBOT FACE} Generated with Claude Code\n", encoding="utf-8")
    assert main([str(clean), str(dirty)]) == 1


def test_allow_patterns_exempt_a_line():
    message = "Fix parser\n\nCo-authored-by: Ai Nguyen <ai@example.com>"
    assert find_violations(message)
    assert find_violations(message, allow_patterns=[re.compile("ai nguyen", re.IGNORECASE)]) == []


def test_main_takes_allow_patterns_from_the_command_line(tmp_path):
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text("Fix x\n\nCo-authored-by: Ai Nguyen <ai@example.com>\n", encoding="utf-8")
    assert main([str(path)]) == 1
    assert main(["--allow-pattern", "ai nguyen", str(path)]) == 0
